
name: CI

# Controls when the action will run. 
# Triggers the workflow on specific pull request events.
on:
  pull_request:
    types: [opened, synchronize]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build-and-test"
  build-and-test:
    # The type of runner that the job will run on
    runs-on: macos-12
    
    timeout-minutes: 5

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_14.2.app
            
    - name: Build and Test
      run: xcodebuild test -project FeedAPIChallenge.xcodeproj -scheme "FeedAPIChallenge" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO SWIFT_TREAT_WARNINGS_AS_ERRORS=YES OTHER_SWIFT_FLAGS="-D ED_SKIP_SWIFT_FORMAT"
